name: blog_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_modular: ^6.3.2
  dartz: ^0.10.1
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.16.0
  firebase_storage: ^11.7.1
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  dotted_border: ^2.1.0
  image_picker: ^1.0.7
  uuid: ^4.4.0
  intl: ^0.19.0
  internet_connection_checker_plus: ^2.3.0
  hive: ^4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true